server:
  port: 8888

alert-api:
  security:
    password: " "
    user: " "
  ## Path to save protobuf files for each agency
  pb-file:
    interval: 30
    out-path: /app/pb/service-alerts_agency_
  ## Time-Zone
  zone: "Europe/Warsaw"
  ## Enable filter out old alerts
  actual-filter: false
  ## Paths to save/read back-up file
  out-path: /app/alerts/alerts.list
  in-path: /app/alerts/alerts.list

##open-api map paths
springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/ui"
