server:
  port: 9991

#logging:
#  file:
#    name: logs/logback.txt

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false

alert-api:
  ## Path to save protobuf file of all alerts
  pb-file:
    out-path: /var/goeuropa.alerts
  ## Time-Zone
  zone: "Europe/Warsaw"
  ## Protobuf file refresh-interval
  refresh-interval: 10
  ## Enable filter out old alerts
  actual-filter: false
  ## Paths to save/read back-up file
  out-path: ./app/resources/alerts.list
  in-path: ./app/resources/alerts.list

##open-api map paths
springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/ui"
