server:
  port: 8888

#logging:
#  file:
#    name: logs/logback.txt

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false

alert-api:
  security:
    password: " "
    user: " "
  ## Path to save protobuf files of alerts
  pb-file:
    interval: 30
    out-path: /app/bp/service-alerts_agency_
  ## Time-Zone
  zone: "Europe/Warsaw"
  ## Enable filter out old alerts
  actual-filter: false
  ## Paths to save/read back-up file
  out-path: /app/alerts/alerts.list
  in-path: /app/alerts/alerts.list

##open-api map paths
springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/ui"
